version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - blog-network

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=blog_db
      - DB_USER=blog_user
      - DB_PASS=blog_password
    networks:
      - blog-network

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  postgres_data:
